spring:
    datasource:
        url: jdbc:mysql://localhost:3306/development_test?serverTimezone=Asia/Tokyo
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root #環境変数化すること
        password: 3113121k #環境変数化すること

    sql:
        init:
            schema-locations:
            - classpath:schema.sql
            data-locations:
            - classpath:data.sql
            encoding: UTF-8
            mode: always

#Log Level出力用
logging:
  level: 
    '[com.example]': debug