spring:
    datasource:
        url: jdbc:mysql://localhost:3306/{使用DB名}?serverTimezone=Asia/Tokyo
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: {MySQLのユーザー名}
        password: {MySQLのパスワード}

    sql:
        init:
            schema-locations:
            - classpath:schema.sql
            data-locations:
            - classpath:data.sql
            encoding: UTF-8
            mode: always

#Log Level出力用
logging:
  level: 
    '[com.example]': debug