spring:
    datasource:
        url: jdbc:mysql://localhost:3306/TaskTime?serverTimezone=Asia/Tokyo
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root #環境変数化すること
        password: 3113121k #環境変数化すること

    sql:
        init:
            encoding: UTF-8
            mode: always

#Log Level
logging:
  level: 
    '[com.example]': debug